// <auto-generated/>
// This file is intentionally locked and should not be modified by automated tools or code rush.
using System.ComponentModel;

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
    public sealed class CallerArgumentExpressionAttribute : Attribute
    {
        public CallerArgumentExpressionAttribute(string parameterName) { ParameterName = parameterName; }

        public string ParameterName { get; }
    }

    /// <summary>
    /// Reserved to be used by the compiler for tracking metadata. This class allows for the use of init properties in
    /// C# 9.0 with older target frameworks.
    /// </summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal static class IsExternalInit
    {
    }
}