using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;
using Workflows.Definition;

namespace Workflows.Runner
{
    public class StateMachineAdvancer
    {
        // Cache that holds the compiled lambda delegates for instant hydration
        // Key: Type of the compiler-generated IAsyncEnumerator
        // Value: Compiled Action(Enumerator, Closure, Locals, State)
        private static readonly ConcurrentDictionary<Type, Action<object, object, object, int>> _hydratorCache
            = new ConcurrentDictionary<Type, Action<object, object, object, int>>();

        public async Task<Wait> RunAsync(
            IAsyncEnumerable<Wait> workflow,
            WorkflowContainer instance,
            object closure,
            object locals,
            int stateAfterWait,
            CancellationToken cancellationToken = default)
        {
            // 1. Get the actual state machine instance generated by Roslyn
            var enumerator = workflow.GetAsyncEnumerator(cancellationToken);
            var enumeratorType = enumerator.GetType();

            // 2. Get or build the compiled hydrator for this specific state machine type
            var hydrator = _hydratorCache.GetOrAdd(enumeratorType, type => BuildHydratorDelegate(type, closure, locals));

            // 3. Hydrate the state machine instantly (Zero Reflection)
            hydrator(enumerator, closure, locals, stateAfterWait);

            // 4. Advance the state machine to the next yield return
            if (await enumerator.MoveNextAsync())
            {
                return enumerator.Current;
            }

            // Workflow completed natively
            return null;
        }

        /// <summary>
        /// Builds a compiled expression tree that sets the internal fields of the compiler-generated state machine.
        /// Equivalent to writing native C#: ((StateMachine)enumerator).<>1__state = state;
        /// </summary>
        private Action<object, object, object, int> BuildHydratorDelegate(Type enumeratorType, object sampleClosure, object sampleLocals)
        {
            // Input parameters for our compiled delegate
            var enumeratorParam = Expression.Parameter(typeof(object), "enumerator");
            var closureParam = Expression.Parameter(typeof(object), "closure");
            var localsParam = Expression.Parameter(typeof(object), "locals");
            var stateParam = Expression.Parameter(typeof(int), "state");

            // Cast the object enumerator to the actual hidden compiler type
            var typedEnumerator = Expression.Convert(enumeratorParam, enumeratorType);
            var assignments = new List<Expression>();

            var fields = enumeratorType.GetFields(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);

            // 1. Assign State: Look for the standard Roslyn state field
            var stateField = fields.FirstOrDefault(f => f.Name == "<>1__state" || f.Name == "state" || f.Name.Contains("state"));
            if (stateField != null)
            {
                var stateAccess = Expression.Field(typedEnumerator, stateField);
                assignments.Add(Expression.Assign(stateAccess, stateParam));
            }

            // 2. Assign Closure
            if (sampleClosure != null)
            {
                var closureType = sampleClosure.GetType();
                var closureField = fields.FirstOrDefault(f => f.FieldType == closureType);
                if (closureField != null)
                {
                    var closureAccess = Expression.Field(typedEnumerator, closureField);
                    var typedClosure = Expression.Convert(closureParam, closureType);
                    assignments.Add(Expression.Assign(closureAccess, typedClosure));
                }
            }

            // 3. Assign Locals
            if (sampleLocals != null)
            {
                var localsType = sampleLocals.GetType();
                var localsField = fields.FirstOrDefault(f => f.FieldType == localsType);
                if (localsField != null)
                {
                    var localsAccess = Expression.Field(typedEnumerator, localsField);
                    var typedLocals = Expression.Convert(localsParam, localsType);
                    assignments.Add(Expression.Assign(localsAccess, typedLocals));
                }
            }

            // Combine all assignments into a single block
            var block = Expression.Block(assignments);

            // Compile to a native Action
            var lambda = Expression.Lambda<Action<object, object, object, int>>(
                block, enumeratorParam, closureParam, localsParam, stateParam);

            return lambda.Compile();
        }
    }
}
