using System;
using System.Collections.Generic;

namespace Workflows.Abstraction.DTOs
{
    /// <summary>
    /// Represents the complete, serialized snapshot of a suspended workflow.
    /// This object contains everything the engine needs to perfectly reconstruct 
    /// the C# compiler-generated state machine and resume execution.
    /// </summary>
    public class StateMachineObject
    {
        /// <summary>
        /// The internal state integer generated by the Roslyn compiler (e.g., <>1__state).
        /// This tells the IAsyncStateMachine exactly which 'yield return' line to resume from.
        /// </summary>
        public int StateIndex { get; set; }

        /// <summary>
        /// The actual workflow class instance defined by the developer (e.g., OrderWorkflow).
        /// This preserves all class-level properties and global state across suspensions.
        /// </summary>
        public object Instance { get; set; }

        /// <summary>
        /// The extracted local variables and closures captured at the time of suspension.
        /// KEY: A unique identifier (Guid) linking this memory block to a specific execution scope or Wait ID.
        /// VALUE: The captured data (e.g., an anonymous closure object or a dictionary of local variables).
        /// </summary>
        public Dictionary<Guid, object> Variables { get; set; } = new();
    }
}
