using System;
using System.Collections.Generic;

namespace Workflows.Abstraction.DTOs
{
    /// <summary>
    /// Represents the complete, serialized snapshot of a suspended workflow.
    /// This object contains everything the engine needs to perfectly reconstruct 
    /// the C# compiler-generated state machine and resume execution.
    /// </summary>
    public class WorkflowStateObject
    {
        public string? WorkflowType { get; set; }
        public string? SubWorkflowMethod { get; set; }

        /// <summary>
        /// The internal state integer generated by the Roslyn compiler (e.g., <>1__state).
        /// This tells the IAsyncStateMachine exactly which 'yield return' line to resume from.
        /// This for root workflow method named "Run"
        /// </summary>
        public int StateIndex { get; set; }

        /// <summary>
        /// The actual workflow class instance defined by the developer (e.g., OrderWorkflow).
        /// This preserves all class-level properties and global state across suspensions.
        /// </summary>
        public object Instance { get; set; }


        /// <summary>
        /// Local state parameters and wait states (keyed by wait Guid or "state") to prevent duplication by value.
        /// </summary>
        public Dictionary<string, object> Locals { get; set; } = new();
    }
}
