using System;
using System.Text;

namespace Workflows.Analyzers
{
    internal static class LayoutClassGenerator
    {
        public static string Generate(string workflowName, int version, WorkflowSchema schema)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"// AUTO-GENERATED by Workflows.VersioningGenerator — DO NOT EDIT");
            sb.AppendLine($"// Archive snapshot of {workflowName} Version {version}");
            sb.AppendLine($"// Schema extracted: {DateTime.UtcNow:O}");
            sb.AppendLine();
            sb.AppendLine($"namespace {schema.AssemblyRootNamespace}.Archive.{workflowName}.V{version}");
            sb.AppendLine("{");

            // ── Instance POCO ────────────────────────────────────────────────────
            sb.AppendLine($"    public sealed class {workflowName}V{version}Instance");
            sb.AppendLine("    {");
            foreach (var prop in schema.StateProperties)
            {
                string nullable = prop.Nullable ? "?" : "";
                sb.AppendLine($"        public {prop.TypeFqn}{nullable} {prop.Name} {{ get; set; }}");
            }
            sb.AppendLine("    }");
            sb.AppendLine();

            // ── State wrapper ────────────────────────────────────────────────────
            sb.AppendLine($"    public sealed class {workflowName}V{version}");
            sb.AppendLine($"        : Workflows.Definition.WorkflowStateWrapper<{workflowName}V{version}Instance>");
            sb.AppendLine("    {");
            sb.AppendLine($"        public {workflowName}V{version}(");
            sb.AppendLine($"            Workflows.Abstraction.DTOs.WorkflowStateDto dto,");
            sb.AppendLine($"            {workflowName}V{version}Instance instance)");
            sb.AppendLine($"            : base(dto, instance) {{ }}");
            sb.AppendLine();

            // Typed pass-through accessors for each state property
            foreach (var prop in schema.StateProperties)
            {
                string nullable = prop.Nullable ? "?" : "";
                sb.AppendLine($"        public {prop.TypeFqn}{nullable} {prop.Name} " +
                              $"=> Instance.{prop.Name};");
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}
